package com.sdi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClientEventTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientEventTypeAllPropertiesEquals(ClientEventType expected, ClientEventType actual) {
        assertClientEventTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertClientEventTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientEventTypeAllUpdatablePropertiesEquals(ClientEventType expected, ClientEventType actual) {
        assertClientEventTypeUpdatableFieldsEquals(expected, actual);
        assertClientEventTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientEventTypeAutoGeneratedPropertiesEquals(ClientEventType expected, ClientEventType actual) {
        assertThat(actual)
            .as("Verify ClientEventType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientEventTypeUpdatableFieldsEquals(ClientEventType expected, ClientEventType actual) {
        assertThat(actual)
            .as("Verify ClientEventType relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCreateDate()).as("check createDate").isEqualTo(expected.getCreateDate()))
            .satisfies(a -> assertThat(a.getUpdateDate()).as("check updateDate").isEqualTo(expected.getUpdateDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientEventTypeUpdatableRelationshipsEquals(ClientEventType expected, ClientEventType actual) {
        // empty method
    }
}
