package com.sdi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClientSizeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientSizeAllPropertiesEquals(ClientSize expected, ClientSize actual) {
        assertClientSizeAutoGeneratedPropertiesEquals(expected, actual);
        assertClientSizeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientSizeAllUpdatablePropertiesEquals(ClientSize expected, ClientSize actual) {
        assertClientSizeUpdatableFieldsEquals(expected, actual);
        assertClientSizeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientSizeAutoGeneratedPropertiesEquals(ClientSize expected, ClientSize actual) {
        assertThat(actual)
            .as("Verify ClientSize auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientSizeUpdatableFieldsEquals(ClientSize expected, ClientSize actual) {
        assertThat(actual)
            .as("Verify ClientSize relevant properties")
            .satisfies(a -> assertThat(a.getSizeName()).as("check sizeName").isEqualTo(expected.getSizeName()))
            .satisfies(a -> assertThat(a.getSizeCode()).as("check sizeCode").isEqualTo(expected.getSizeCode()))
            .satisfies(a -> assertThat(a.getSizeDescription()).as("check sizeDescription").isEqualTo(expected.getSizeDescription()))
            .satisfies(a -> assertThat(a.getCreateDate()).as("check createDate").isEqualTo(expected.getCreateDate()))
            .satisfies(a -> assertThat(a.getUpdateDate()).as("check updateDate").isEqualTo(expected.getUpdateDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientSizeUpdatableRelationshipsEquals(ClientSize expected, ClientSize actual) {
        // empty method
    }
}
