package com.sdi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClientTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientTypeAllPropertiesEquals(ClientType expected, ClientType actual) {
        assertClientTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertClientTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientTypeAllUpdatablePropertiesEquals(ClientType expected, ClientType actual) {
        assertClientTypeUpdatableFieldsEquals(expected, actual);
        assertClientTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientTypeAutoGeneratedPropertiesEquals(ClientType expected, ClientType actual) {
        assertThat(actual)
            .as("Verify ClientType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientTypeUpdatableFieldsEquals(ClientType expected, ClientType actual) {
        assertThat(actual)
            .as("Verify ClientType relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getCreateDate()).as("check createDate").isEqualTo(expected.getCreateDate()))
            .satisfies(a -> assertThat(a.getUpdateDate()).as("check updateDate").isEqualTo(expected.getUpdateDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientTypeUpdatableRelationshipsEquals(ClientType expected, ClientType actual) {
        // empty method
    }
}
