package com.sdi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ComponentTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComponentTypeAllPropertiesEquals(ComponentType expected, ComponentType actual) {
        assertComponentTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertComponentTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComponentTypeAllUpdatablePropertiesEquals(ComponentType expected, ComponentType actual) {
        assertComponentTypeUpdatableFieldsEquals(expected, actual);
        assertComponentTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComponentTypeAutoGeneratedPropertiesEquals(ComponentType expected, ComponentType actual) {
        assertThat(actual)
            .as("Verify ComponentType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComponentTypeUpdatableFieldsEquals(ComponentType expected, ComponentType actual) {
        assertThat(actual)
            .as("Verify ComponentType relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComponentTypeUpdatableRelationshipsEquals(ComponentType expected, ComponentType actual) {
        // empty method
    }
}
