package com.sdi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DeployementTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeployementTypeAllPropertiesEquals(DeployementType expected, DeployementType actual) {
        assertDeployementTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertDeployementTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeployementTypeAllUpdatablePropertiesEquals(DeployementType expected, DeployementType actual) {
        assertDeployementTypeUpdatableFieldsEquals(expected, actual);
        assertDeployementTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeployementTypeAutoGeneratedPropertiesEquals(DeployementType expected, DeployementType actual) {
        assertThat(actual)
            .as("Verify DeployementType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeployementTypeUpdatableFieldsEquals(DeployementType expected, DeployementType actual) {
        assertThat(actual)
            .as("Verify DeployementType relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getCreateDate()).as("check createDate").isEqualTo(expected.getCreateDate()))
            .satisfies(a -> assertThat(a.getUpdateDate()).as("check updateDate").isEqualTo(expected.getUpdateDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeployementTypeUpdatableRelationshipsEquals(DeployementType expected, DeployementType actual) {
        // empty method
    }
}
